data:
    name: 'synthetic_shapes'
    primitives: 'all'
    truncate: {draw_ellipses: 0.3, draw_stripes: 0.2, gaussian_noise: 0.1}
    cache_in_memory: true
    validation_size: 500
    suffix: 'v6'
    add_augmentation_to_test_set: false  # set to true to evaluate with noise
    preprocessing:
        blur_size: 21
        resize: [120, 160]  # Should be multiples of 8
    augmentation:
        photometric:
            enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 75}
                random_contrast: {strength_range: [0.3, 1.8]}
                additive_gaussian_noise: {stddev_range: [0, 15]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.8]
                    kernel_size_range: [50, 100]
                motion_blur: {max_kernel_size: 7}
        homographic:
            enable: true
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.8
                max_angle: 1.57  # 3.14
                allow_artifacts: true
                translation_overflow: 0.05
            valid_border_margin: 2
model:
    name: 'magic_point'
    batch_size: 64
    eval_batch_size: 50
    learning_rate: 0.001
    kernel_reg: 0.
    detection_threshold: 0.001 # 1/65
    nms: 4
train_iter: 50000
eval_iter: 200
validation_interval: 1000
seed: 0
#save_interval: 5000
#keep_checkpoints: 20
