data:
    name: 'patches_dataset'
    dataset: 'hpatches'  # 'coco' 'hpatches'
    alteration: 'all'  # 'all' 'i' 'v'
    preprocessing:
        resize: [240, 320]  # [240, 320] for HPatches and False for coco
model:
    name: 'magic_point'
    batch_size: 50
    eval_batch_size: 50
    learning_rate: 0.001
    detection_threshold: 0.001
    nms: 4
    top_k: 1000
    homography_adaptation:
        num: 0
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.1
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            allow_artifacts: true
            patch_ratio: 0.5
eval_iter: 1000
